nerves-hub/nerves_hub_cli

- lib/mix/tasks/nerves_hub.deployment.ex
- lib/mix/tasks/nerves_hub.device.ex
- lib/mix/tasks/nerves_hub.key.ex
- lib/mix/tasks/nerves_hub.user.ex
This has various small updates to help text in throughout the CLI. It turns out that most Elixir commands use all caps for required arguments so I did too.
> Various updates to the help text

- lib/mix/tasks/nerves_hub.deployment.ex
- lib/nerves_hub_cli/api/deployment.ex
Adds the following mix tasks
* `nerves_hub.deployment create` - Create a new deployment
> Add nerves_hub.deployment create

- lib/mix/tasks/nerves_hub.device.ex
This renames the command 
`mix nerves_hub.device provision IDENTIFIER`
to
`mix nerves_hub.device burn IDENTIFIER`
It will configure the environment and delegate to `mix firmware.burn`. If the device certificates are not present, it will raise and inform the user they need to create the certificates first.
> Rename nerves_hub.device 'provision' to  'burn'

- lib/mix/nerves_hub/utils.ex
- lib/mix/tasks/nerves_hub.firmware.ex
Noticed this during your keynote 😄
> Fix mispelling of organization

- lib/mix/tasks/nerves_hub.user.ex
- lib/nerves_hub_cli/api/user.ex
This will allow the CLI to continue to work after this change https://github.com/nerves-hub/nerves_hub_web/pull/253
> Change name to username for accounts

- README.md
- lib/mix/nerves_hub/shell.ex
- lib/mix/tasks/nerves_hub.firmware.ex
Use case for this is mostly for signing firmware
on CI.
Fixes #32
> Add support for loading fwup keys from env.

- lib/mix/tasks/nerves_hub.key.ex
- lib/mix/tasks/nerves_hub.user.ex
This task will allow exporting of both user certs and fwup signing keys.
Fixes #10
> Add task to export signing keys and certs.

- lib/mix/tasks/nerves_hub.device.ex
- lib/nerves_hub_cli/api/device.ex
This will require https://github.com/nerves-hub/nerves_hub_web/pull/276
This allows updating devices info from mix.
> Add ability to update device info

- README.md
- lib/mix/nerves_hub/shell.ex
- lib/mix/tasks/nerves_hub.firmware.ex
- lib/mix/tasks/nerves_hub.key.ex
- lib/mix/tasks/nerves_hub.product.ex
- lib/mix/tasks/nerves_hub.user.ex
This is useful for `firmware publish` on CI
> Add option to force (y)

- lib/mix/tasks/nerves_hub.product.ex
- lib/mix/tasks/nerves_hub.user.ex
This PR contains some text updates I made while going through the getting started instructions again.
> Update the help text and defaults for mix nerves_hub.product

- README.md
- lib/mix/nerves_hub/shell.ex
- lib/mix/tasks/nerves_hub.key.ex
- lib/mix/tasks/nerves_hub.user.ex
- lib/nerves_hub_cli/key.ex
I find knowing which password to use each time I'm prompted a little confusing. The main commit in this serious adds more text around the prompts in the hopes that this makes it simpler. I also added a bit more text when creating signing keys.
> Minor text/dialyzer updates and add text for keys

- lib/mix/tasks/nerves_hub.firmware.ex
> Extract product before trying product in meta

- lib/mix/nerves_hub/shell.ex
> Make sure to exit with a status code to halt CI

- lib/mix/tasks/nerves_hub.ca_certificate.ex
This more accurately describes what those operations do. I.e., they
don't actually create or delete certificates. They manage the
CA certificates that are known to the NervesHub server.
> Rename ca_certificate create/delete to register/unregister

- lib/mix/tasks/nerves_hub.device.ex
Saw a little typo during training!
> Fix typo in shell message

- lib/mix/tasks/nerves_hub.device.ex
> Fix TableRex error when no devices

- lib/mix/tasks/nerves_hub.device.ex
> Add filtering to device list command

- lib/mix/nerves_hub/shell.ex
Issue #110
Allow a user @password_retries_allowed (shell.ex) attempts to enter a correct password.
> Allow user to retry entering password

- lib/mix/tasks/nerves_hub.device.ex
- mix.exs
- mix.lock
Depends on https://github.com/nerves-hub/nerves_hub_user_api/pull/17
> Move devices under products

- lib/mix/tasks/nerves_hub.user.ex
This updates the match and messages to support logging in using an account username or email.
> Support Email/Username login

- lib/mix/tasks/nerves_hub.device.ex
Around Nerves, the words "signing certificate", "CA certificate",
"issuer certificate" and "signer certificate" are used mostly
interchangably. This commit changes documentation and unreleased mix
helper options to be consistent with the term "signer certificate".
> Use the term signer certificate consistently

- lib/mix/tasks/nerves_hub.ca_certificate.ex
depends on nerves-hub/nerves_hub_user_api#23
> Adds description option to ca cert

- lib/mix/tasks/nerves_hub.device.ex
This allows importing existing trusted device certificates.
> Add device cert import

- lib/mix/tasks/nerves_hub.ca_certificate.ex
The description is in the web UI. This brings it to the CLI.
> Add cert description to ca_certificate list

- README.md
- config/staging.exs
I'm working to make it easier to connect to a staging environment.
> Add config for staging environment

- lib/mix/tasks/nerves_hub.ca_certificate.ex
- lib/mix/tasks/nerves_hub.deployment.ex
- lib/mix/tasks/nerves_hub.device.ex
- lib/mix/tasks/nerves_hub.firmware.ex
- lib/mix/tasks/nerves_hub.key.ex
- lib/mix/tasks/nerves_hub.org.ex
- lib/mix/tasks/nerves_hub.product.ex
- lib/mix/tasks/nerves_hub.user.ex
This was a tricky one to solve in a "not awful" way. Found the solution [here](https://groups.google.com/g/elixir-lang-talk/c/JikyDaoGP9k)
> Force compile user code to ensure that CA certs can be loaded

- lib/nerves_hub_cli/cli/product.ex
> fix ok tuple for delete product

- lib/nerves_hub_cli/entry_point.ex
> Fix the entry point so we can run tests
