- lib/mix/nerves_hub/shell.ex
- lib/mix/nerves_hub/utils.ex
- lib/mix/tasks/nerves_hub.deployment.ex
- lib/mix/tasks/nerves_hub.firmware.ex
- lib/mix/tasks/nerves_hub.key.ex
- lib/nerves_hub_cli.ex
- lib/nerves_hub_cli/api/key.ex
- lib/nerves_hub_cli/application.ex
- lib/nerves_hub_cli/key.ex
- lib/nerves_hub_cli/user.ex
Add the following mix tasks:
* `nerves_hub.key list` -list all keys in the org
* `nerves_hub.key create [name]` - create a new key with the specified name
* `nerves_hub.key delete [name]` - delete the key with the specified name
All the key operations can take the boolean flag `--local` to only apply the operation to the local computer.
> Add CLI for managing keys and enhance user certificates

- lib/mix/nerves_hub/utils.ex
- lib/mix/tasks/nerves_hub.deployment.ex
- lib/mix/tasks/nerves_hub.device.ex
This PR adds the mix command
`nerves_hub.device provision [identifier]`
If called with no command line options, it will attempt to create a new certificate for the device, register it with the server, configure the environment, and call `mix firmware.burn`.
You can specify a location where you wish to place the temporary certificate files by passing `--path`. If a certificate for the device already exists at that path, you will be asked if you wish to use them or create new ones. You can also pass `--key` and `--cert` to specify which key and cert files to use.
> Add mix command to make it easier to provision a device.

- lib/mix/tasks/nerves_hub.product.ex
- lib/nerves_hub_cli/api/product.ex
This PR allows the management of products from the command line.
It adds the following mix tasks
* `nerves_hub.product list`
* `nerves_hub.product create`
* `nerves_hub.product delete PRODUCT_NAME`
* `nerves_hub.product update PRODUCT_NAME KEY VALUE`
Depends on https://github.com/nerves-hub/nerves_hub_web/pull/222
> Add CLI for managing products

- .gitignore
- lib/mix/tasks/nerves_hub.device.ex
Instead of placing generated device certificate files in the current working directory, this PR will create / use a folder `nerves-hub` in the current working directory.
> Store generated certificates in a `nerves-hub` folder in cwd

- lib/mix/nerves_hub/shell.ex
- lib/nerves_hub_cli.ex
* `NERVES_HUB_FW_PRIVATE_KEY` and `NERVES_HUB_FW_PUBLIC_KEY` were
backwards.
* `NERVES_HUB_CERT` and `NERVES_HUB_KEY` needed to be converted to pem
* Allow loading `NERVES_HUB_FW_PUBLIC_KEY` into `NervesHub.public_keys()`
> Fix loading params from env vars.

- lib/mix/tasks/nerves_hub.firmware.ex
- lib/nerves_hub_cli/api.ex
- lib/nerves_hub_cli/api/firmware.ex
This PR adds support for setting the firmware `ttl` on firmware records. As a side effect, it also contains an added progress bar for firmware uploads.
Requires this PR https://github.com/nerves-hub/nerves_hub_web/pull/284
Fixes https://github.com/nerves-hub/nerves_hub_cli/issues/13
> Add support for setting firmware ttl

- lib/mix/nerves_hub/shell.ex
- lib/mix/tasks/nerves_hub.device.ex
- lib/mix/tasks/nerves_hub.user.ex
- lib/nerves_hub_cli/certificate.ex
- lib/nerves_hub_cli/crypto.ex
- lib/nerves_hub_cli/device.ex
- lib/nerves_hub_cli/user.ex
- mix.exs
- mix.lock
The `x509` package wraps and extends Erlang's built-in certificate management routines. While not perfect, it removes a runtime dependency on openssl's CLI and it slightly easier to understand and use.
> Replace calls to openssl with the x509 package

- lib/mix/nerves_hub/shell.ex
- lib/nerves_hub_cli/api.ex
- lib/nerves_hub_cli/application.ex
- mix.exs
- mix.lock
I prefer Tesla as an HTTP Client because it should hopefully allow us to easily write some tests based on fixtures. This still uses the `hackney` adapter to do the clientside ssl stuff, just wrapped in an abstraction.
> Use Tesla as HTTP Client

- lib/mix/nerves_hub/shell.ex
Storing multiline certificate and keys in environment variables can be problematic on CI providers and is sometimes recommended that they be base64 encoded. This PR will try to `Base.decode64` the values to naturally support this case.
> Try to decode64 cert and key from env

- lib/mix/tasks/nerves_hub.device.ex
The latest version of nerves alters `mix firmware.burn` to both call `mix firmware` and the new `mix burn`. When burning a provisioned devices firmware, its better to just call `burn` and not alter the firmware again.
> Call mix burn instead of mix firmware.burn

- lib/mix/tasks/nerves_hub.ca_certificate.ex
- lib/nerves_hub_cli/api/ca_certificate.ex
Adds the following mix commands
* `nerves_hub.ca_certificate list` - list all ca certificates.
* `nerves_hub.ca_certificate create CERT_PATH` - create a new ca_certificate record from the supplied pem certificate path.
* `nerves_hub.ca_certificate delete CERT_SERIAL` - delete the ca certificate with the supplied serial.
depends on https://github.com/nerves-hub/nerves_hub_web/pull/304
> Add mix commands for managing ca certificates

- lib/mix/tasks/nerves_hub.firmware.ex
I clicked the wrong buttons. I think we should revert this. The server derives everything it knows from the firmware metadata so I don't think this method will work.
Reverts nerves-hub/nerves_hub_cli#65
> Revert "Extract product before trying product in meta"

- lib/mix/nerves_hub/utils.ex
Configuring `nerves_hub` from the mix.exs file prevents the configuration from being accessible when compiling dependencies. Moving this to the application config not only fixes the scoping issue, but has the added benefit of organizing all the config in one place.
> Move nerves_hub config from mix project to config.exs

- lib/mix/tasks/nerves_hub.user.ex
This should call the password_get functions we have in Shell instead of trying to call out to hex.
Fixes an issue where calling `mix nerves_hub.user auth` results in an error when requesting the password.
```
** (exit) exited in: GenServer.call(Hex.State, {:get, {Map, :fetch, [:clean_pass]}}, 5000)
** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
(elixir) lib/gen_server.ex:958: GenServer.call/3
lib/hex/state.ex:82: Hex.State.fetch!/1
lib/mix/tasks/hex.ex:310: Mix.Tasks.Hex.password_get/1
(nerves_hub_cli) lib/mix/tasks/nerves_hub.user.ex:131: Mix.Tasks.NervesHub.User.auth/0
(mix) lib/mix/task.ex:331: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```
> Use Shell password_get instead of Hex

- lib/mix/nerves_hub/utils.ex
- lib/mix/tasks/nerves_hub.deployment.ex
- lib/mix/tasks/nerves_hub.device.ex
- test/nerves_hub_cli_test.exs
This should remove some confusion on comma vs. space separated tags.
The prompts now tell you to separate tags with commas and it errors out
if you try to have a space in a tag. While it had been possible to have
spaces in tags, it was really confusing to see them printed and when
they were added, it was an accident.
This also updates the `--tag` option so that if you pass `--tag a,b,c`,
it will turn into 3 tags. This is the same behavior as `--tag a --tag b
--tag c`, but shorter and without the need to parse tags in programs
calling `mix nerves_hub.device create`.
> Support comma separated tags everywhere

- lib/mix/tasks/nerves_hub.device.ex
Include the device UUID in the `nerves_hub.device` list task report.
Issue #102 
Also required a change in `nerves_hub_web` to return the UUID: https://github.com/nerves-hub/nerves_hub_web/pull/454
> Include a device`s UUID for the device list task

- lib/mix/tasks/nerves_hub.key.ex
- lib/nerves_hub_cli/key.ex
The key.ex one is more subtle than it looks. The error from that function, `{:error, :enoent}` propagated through quite a few functions before being printed so the context was lost. This makes it a little better. Fwiw, the root cause was that the organization I was using was set incorrectly.
> Improve error messages

- lib/mix/nerves_hub/shell.ex
While investigating  #131, i noticed the error messages weren't be printed properly. This fixes that
> Add clause to print standard binary error messages

- lib/mix/tasks/nerves_hub.device.ex
Requires https://github.com/nerves-project/nerves/pull/474.
Updates `mix nerves_hub.device burn` to allow passing `--firmware <path to .fw>`. The flag ultimately gets consumed by the work in the required PR above.
This is convenient in the case where you want to provision a device with an arbitrary .fw.
> Allow the path to the fw to be passed to mix nerves_hub.device burn

- README.md
- lib/mix/nerves_hub/utils.ex
- lib/nerves_hub_cli.ex
For whatever reason, relying on a `:nerves_hub` config value for finding an org just doesn't jive with me.
So instead, lets look for `:nerves_hub_cli, :org` value to fetch from the project.
Also change `NervesHubCLI.resolve_fwup_public_keys/2` to allow supplying an org to use for the resolution.
This function is called from `:nerves_hub` and adding a second arg would allow `:nerves_hub` to handle
its own settings and pass its config values where needed to the CLI rather than coupling `:nerves_hub`
project config within `:nerves_hub_cli`
Once merged and released, I'll adjust `:nerves_hub` to use the new `NervesHubCLI.resolve_fwup_public_keys/2`
> Decouple :nerves_hub

- lib/mix/tasks/nerves_hub.device.ex
- lib/nerves_hub_cli/certificate.ex
Some cases may require someone to create a cert/key with their own issuer which is quite an involved process right now. (and dealing with user error around SSL is a nightmare to troubleshoot..)
So this just adds a convenience `nerves_hub.device cert create` task to allow specifying your own `--issuer` and `--issuer-key` to be used for creating the device cert and key according to the structure and template NervesHub expects.
The `NervesHub.Certificate` module is pretty much ripped straight from [`NervesHubCA.CertificateTemplate`](https://github.com/nerves-hub/nerves_hub_ca/blob/master/lib/nerves_hub_ca/certificate_template.ex). There is probably a better way to do this, but I think its pretty niche use-case and wanted to get _something_ working...cause I need it 😆
> Allow using issuer CA cert and key locally

- lib/mix/nerves_hub/shell.ex
The `base64` tool on linux can create whitespace in it's output
> Allow bas64 decoder to ignore whitespace

- lib/mix/nerves_hub/bulk.ex
- lib/mix/tasks/nerves_hub.device.ex
After using this a bit, I thought it would be nice to have some useful results output. So this adds that 🎉 
Specifically:
* Reports error details per device
* Shows when the CSV line is unexpected format and tries to deduce line number for the malformed line
* General report at the end with number of errors, malformed lines, and successful requests
> add some formatting to nerves_hub.device bulk_create

- lib/mix/tasks/nerves_hub.deployment.ex
Part of https://github.com/nerves-hub/nerves_hub_web/issues/641
Requires https://github.com/nerves-hub/nerves_hub_web/pull/642 be deployed
NervesHub has been adapted to reference a deployment state as `on/off` instead of `active/inactive`
This updates to reflect that change to more closely match the web UI and (hopefully) reduce confusion.
```
Deployments:
------------
name:      Testing
state:     off
firmware:  46f5d7d2-6ae9-5d3f-7638-3e46ca6220ec
conditions:
device tags: [dont-use-me]
------------
```
> Change Deployment is_active -> state

- lib/mix/tasks/nerves_hub.user.ex
Users have the ability to change the home dir for the CLI config files and so it may not always be `~/.nerves-hub` like the output says when authenticating a user and creating the auth cert/key.
So this changes the output to read the home dir that NervesHubCLI has been configured to use
> More specific location output when creating user auth cert

- lib/mix/tasks/nerves_hub.device.ex
This fixes errors like the one below which are caused by devices not having any tags (or `tags: nil`)
```
jonjon@bender:~/repos/nerves_hub_cli$ mix nerves_hub.device list --product poser
NervesHub server: 0.0.0.0:4002
NervesHub organization: jonjon
Local NervesHub user password:
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): GenEvent.Stream, HashDict, MapSet, Function, Date.Range, List, HashSet, Stream, Range, IO.Stream, File.Stream, Map
(elixir 1.11.2) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir 1.11.2) lib/enum.ex:141: Enumerable.reduce/3
(elixir 1.11.2) lib/enum.ex:3461: Enum.join/2
(nerves_hub_cli 0.10.4) lib/mix/tasks/nerves_hub.device.ex:530: anonymous fn/1 in …
```
> Fix error rendering devices without a tag

- lib/mix/nerves_hub/utils.ex
- lib/mix/tasks/nerves_hub.ca_certificate.ex
- lib/mix/tasks/nerves_hub.device.ex
The web UI was recently changed to display certificate serial numbers as hex. This updates `nerves_hub.ca_certificate` functions to also display the serial as hex as well. It also adjusts `nerves_hub.ca_certificate unregister` to support using the hex or interger representation of the serial as well
> Support CA Certificate serial as hex

- lib/mix/tasks/nerves_hub.device.ex
- lib/mix/tasks/nerves_hub.key.ex
- lib/mix/tasks/nerves_hub.user.ex
This module attribute was defaulting the `nerves-hub` dir of the current
directory in a few places. However, this breaks the expectation when
setting `:home_dir` or `NERVES_HUB_HOME`.
This changes removes the module attribute in those places and uses
`NervesHubCLI.home_dir/0` instead
> Remove uses of @data-dir

- lib/mix/nerves_hub/shell.ex
Due to the presence of the two mistakes, it was seemed to be ok from the outside of request_keys function.
This commit fix the two,
* mismatch between a variable name and its value
* return tuple's variable order
> Fix a mismatch between a variable name and its value

- mix.exs
`mix deps.update --all` will still download `pbcs 0.1.3`. It shows a
warning, but some people ignore it. This prevents 0.1.3 from being used.
> Avoid broken pbcs 0.1.3

- .circleci/config.yml
- lib/mix/tasks/nerves_hub.device.ex
- mix.exs
* remove deprecated `:race_conditions` dialyzer option
* Add new `:missing_return` and `:extra_return` dialyzer options
* Update Elixir/Erlang CI versions
> Support OTP 25

- lib/mix/tasks/nerves_hub.device.ex
- lib/nerves_hub_cli/api/device.ex
- lib/nerves_hub_cli/api/device_certificate.ex
- lib/nerves_hub_cli/api/user.ex
This requires NervesHubCA which is deprecated.
> Remove signing devices (and users) by NervesHubWeb

- README.md
- config/config.exs
- config/dev.exs
- config/docs.exs
- config/prod.exs
- config/staging.exs
- config/test.exs
- lib/nerves_hub_cli/api.ex
- remove nerves-hub.org defaults
- remove mention of these defaults in the readme
- remove the environment configs, they aren't used
- and support a `uri` config which includes all the host, port, scheme bits needed
> support a slightly simpler config for host, port, and scheme

- lib/nerves_hub_cli/api.ex
http2 file uploads were causing consistent errors due to the window size not being updated by the mint adapter
https://github.com/elixir-tesla/tesla/issues/394
this change locks the api to use http1, with a timeout of 5mins (large uploads)
> prefer http1 for file uploads

- .circleci/config.yml
- .gitignore
- README.md
- lib/mix/tasks/nerves_hub.firmware.ex
- lib/nerves_hub_cli/api.ex
- lib/nerves_hub_cli/cli.ex
- lib/nerves_hub_cli/cli/bulk.ex
- lib/nerves_hub_cli/cli/ca_certificate.ex
- lib/nerves_hub_cli/cli/config.ex
- lib/nerves_hub_cli/cli/deployment.ex
- lib/nerves_hub_cli/cli/device.ex
- lib/nerves_hub_cli/cli/firmware.ex
- lib/nerves_hub_cli/cli/key.ex
- lib/nerves_hub_cli/cli/org.ex
- lib/nerves_hub_cli/cli/product.ex
- lib/nerves_hub_cli/cli/shell.ex
- lib/nerves_hub_cli/cli/user.ex
- lib/nerves_hub_cli/cli/utils.ex
- mix.exs
I added support to install NervesHubCLI as an escript, to evaluate whether this provides a better experience for working with NervesHub from the command line without configuring it with every project. It's quite rough around the edges
I recently was invited to try out the NervesCloud beta by Lars and Josh. This was my first time setting up NervesHub, and unfortunately I found the process to be confusing. While NervesHubLink makes sense to add as a project dependency, I couldn't quite figure out how to work with the mix tasks for the CLI. 
I know that 2.0 is under active development and the docs are getting better with every commit, and that definitely would have helped with some of the issues I faced. However, one of the most confusing parts of this was configuring the CLI to correctly …
> Support a globally-installable escript

- lib/nerves_hub_cli/cli/utils.ex
This copy/pastes the relevant getting started instructions from the
README.md so that new users don't have to look.
> Add first-time help when the URI isn't set

- .tool-versions
Without the -otp-27, Elixir is compiled for an earlier version of OTP.
It doesn't look like it currently matters for this project, but it could
in the future.
> Use Elixir as compiled for OTP 27
